# Generated by Django 3.2.19 on 2023-05-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0002_auto_20230525_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcot',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
